# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bugtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('assign_to', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=20)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUM'), ('H', 'HIGH')], max_length=2)),
                ('created_on', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
